2025-03-23 03:20:36,114 DEBUG    root            Loaded Command Group: ['gcloud', 'projects']
2025-03-23 03:20:36,118 DEBUG    root            Loaded Command Group: ['gcloud', 'projects', 'get_iam_policy']
2025-03-23 03:20:36,119 DEBUG    root            Running [gcloud.projects.get-iam-policy] with arguments: [--format: "table(bindings.role, bindings.members)", PROJECT_ID_OR_NUMBER: "mywebproject-420221"]
2025-03-23 03:20:36,130 DEBUG    urllib3.connectionpool Starting new HTTPS connection (1): cloudresourcemanager.googleapis.com:443
2025-03-23 03:20:37,129 DEBUG    urllib3.connectionpool https://cloudresourcemanager.googleapis.com:443 "POST /v1/projects/mywebproject-420221:getIamPolicy?alt=json HTTP/11" 403 None
2025-03-23 03:20:37,133 DEBUG    root            (gcloud.projects.get-iam-policy) [weitingchen0502@gmail.com] does not have permission to access projects instance [mywebproject-420221:getIamPolicy] (or it may not exist): The caller does not have permission. This command is authenticated as weitingchen0502@gmail.com which is the active account specified by the [core/account] property
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/google-cloud-sdk/515.0.0/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 981, in Execute
    resources = calliope_command.Run(cli=self, args=args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/google-cloud-sdk/515.0.0/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 934, in Run
    resources = command_instance.Run(args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/google-cloud-sdk/515.0.0/google-cloud-sdk/lib/surface/projects/get_iam_policy.py", line 48, in Run
    return projects_api.GetIamPolicy(project_ref)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/google-cloud-sdk/515.0.0/google-cloud-sdk/lib/googlecloudsdk/api_lib/cloudresourcemanager/projects_api.py", line 227, in GetIamPolicy
    return client.projects.GetIamPolicy(policy_request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/google-cloud-sdk/515.0.0/google-cloud-sdk/lib/googlecloudsdk/generated_clients/apis/cloudresourcemanager/v1/cloudresourcemanager_v1_client.py", line 836, in GetIamPolicy
    return self._RunMethod(
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/google-cloud-sdk/515.0.0/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 747, in _RunMethod
    return self.ProcessHttpResponse(method_config, http_response, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/google-cloud-sdk/515.0.0/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 753, in ProcessHttpResponse
    self.__ProcessHttpResponse(method_config, http_response, request))
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/google-cloud-sdk/515.0.0/google-cloud-sdk/lib/third_party/apitools/base/py/base_api.py", line 612, in __ProcessHttpResponse
    raise exceptions.HttpError.FromResponse(
apitools.base.py.exceptions.HttpForbiddenError: HttpError accessing <https://cloudresourcemanager.googleapis.com/v1/projects/mywebproject-420221:getIamPolicy?alt=json>: response: <{'vary': 'Origin, X-Origin, Referer', 'content-type': 'application/json; charset=UTF-8', 'content-encoding': 'gzip', 'date': 'Sun, 23 Mar 2025 02:20:37 GMT', 'server': 'ESF', 'x-xss-protection': '0', 'x-frame-options': 'SAMEORIGIN', 'x-content-type-options': 'nosniff', 'server-timing': 'gfet4t7; dur=774', 'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000', 'transfer-encoding': 'chunked', 'status': 403}>, content <{
  "error": {
    "code": 403,
    "message": "The caller does not have permission",
    "status": "PERMISSION_DENIED"
  }
}
>
2025-03-23 03:20:37,137 ERROR    root            (gcloud.projects.get-iam-policy) [weitingchen0502@gmail.com] does not have permission to access projects instance [mywebproject-420221:getIamPolicy] (or it may not exist): The caller does not have permission. This command is authenticated as weitingchen0502@gmail.com which is the active account specified by the [core/account] property
